name: Docker Build Native

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Check java version
      run: java --version
    
    - name: Set execute permission for gradlew
      run: chmod +x gradlew

    - name: Build the project with Gradle
      run: ./gradlew build -Dquarkus.package.type=native
      
    - name: Build the Docker image (Native)
      run: docker build -f src/main/docker/Dockerfile.native -t quarkus/quarkus-build-poc-native .
