name: Managed Ubuntu Build Publish Deploy Test (JVM)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21    
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'
      if: runner.os == 'Linux'

    - name: Check java version
      run: java --version
    
    - name: Set execute permission for gradlew
      run: chmod +x gradlew
      if: runner.os == 'Linux'

    - name: Build the project with Gradle
      run: ./gradlew build
      
    - name: Build the Docker image (JVM)
      run: docker build -f src/main/docker/Dockerfile.jvm -t quarkus/code-with-quarkus-jvm .
    
    - name: Tag the image
      run: docker tag quarkus/code-with-quarkus-jvm:latest ${{ secrets.DOCKERHUB_USERNAME }}/code-with-quarkus:latest
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/code-with-quarkus:latest
    
    - name: Deploy Container
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/code-with-quarkus:latest
        docker run -i -d --rm -p 8080:8080 --name code-with-quarkus ${{ secrets.DOCKERHUB_USERNAME }}/code-with-quarkus:latest
        docker ps
        
    - name: Stop Container
      run: docker stop code-with-quarkus
