name: Self-Hosted Build Publish Deploy Test (JVM)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21    
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'
      if: runner.os == 'Linux'

    - name: Check java version
      run: java --version
    
    - name: Set execute permission for gradlew
      run: chmod +x gradlew
      if: runner.os == 'Linux'

    - name: Build the project with Gradle
      run: ./gradlew build
      
    - name: Build the Docker image (JVM)
      run: docker build -f src/main/docker/Dockerfile.jvm -t quarkus/code-with-quarkus-jvm .

  publish:
    runs-on: self-hosted
    needs: build

    steps:
    
    - name: Tag the image
      run: docker tag quarkus/code-with-quarkus-jvm:latest zeeshansiddiquirp/code-with-quarkus:latest
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      run: docker push zeeshansiddiquirp/code-with-quarkus:latest

  deploy:
    runs-on: self-hosted
    needs: publish

    steps:        
    
    - name: Deploy Container
      run: |
        docker pull zeeshansiddiquirp/code-with-quarkus:latest
        docker run -i -d --rm -p 8080:8080 --name code-with-quarkus-jvm quarkus/code-with-quarkus-jvm
        docker ps

  test:
    runs-on: self-hosted
    needs: deploy

    steps:
    
    - name: Test Container (Windows)
      run: Invoke-WebRequest -URI http://localhost:8080/hello
      if: runner.os == 'Windows'
      
    - name: Test Container (Linux)
      run: curl http://localhost:8080/hello
      if: runner.os == 'Linux'
        
    - name: Stop Container
      run: docker stop code-with-quarkus-jvm
